language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
after_success:
  - npm install -g codeclimate-test-reporter
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codeclimate-test-reporter < lcov.info
